# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\DELL\Documents\IPC2_Proyecto2_201445840\ventanas\carga_manual.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.frame.setMinimumSize(QtCore.QSize(800, 600))
        self.frame.setMaximumSize(QtCore.QSize(800, 600))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"\n"
"\n"
"QLabel{\n"
"color: rgb(18, 82, 200);\n"
"\n"
"font: 75 12pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QLabel:hover{\n"
"color: white;\n"
"\n"
"\n"
"font: 75 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Arial\";\n"
"    \n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Arial\";\n"
"    \n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bt_regresar = QtWidgets.QPushButton(self.frame)
        self.bt_regresar.setGeometry(QtCore.QRect(650, 550, 141, 40))
        self.bt_regresar.setMinimumSize(QtCore.QSize(100, 40))
        self.bt_regresar.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\IPC2_Proyecto2_201445840\\ventanas\\../imagenes/pngfind.com-back-png-1934895.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_regresar.setIcon(icon)
        self.bt_regresar.setIconSize(QtCore.QSize(32, 32))
        self.bt_regresar.setObjectName("bt_regresar")
        self.btnmanual = QtWidgets.QPushButton(self.frame)
        self.btnmanual.setGeometry(QtCore.QRect(490, 100, 201, 40))
        self.btnmanual.setMinimumSize(QtCore.QSize(100, 40))
        self.btnmanual.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\IPC2_Proyecto2_201445840\\ventanas\\../imagenes/escritura.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnmanual.setIcon(icon1)
        self.btnmanual.setIconSize(QtCore.QSize(32, 32))
        self.btnmanual.setObjectName("btnmanual")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(30, 0, 400, 35))
        self.label_8.setMinimumSize(QtCore.QSize(400, 35))
        self.label_8.setMaximumSize(QtCore.QSize(200, 30))
        self.label_8.setObjectName("label_8")
        self.lineEditpaciente = QtWidgets.QLineEdit(self.frame)
        self.lineEditpaciente.setGeometry(QtCore.QRect(240, 50, 231, 20))
        self.lineEditpaciente.setObjectName("lineEditpaciente")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(30, 50, 200, 35))
        self.label_9.setMinimumSize(QtCore.QSize(200, 35))
        self.label_9.setMaximumSize(QtCore.QSize(200, 30))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(30, 80, 200, 35))
        self.label_10.setMinimumSize(QtCore.QSize(200, 35))
        self.label_10.setMaximumSize(QtCore.QSize(200, 30))
        self.label_10.setObjectName("label_10")
        self.lineEditpaciente_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEditpaciente_2.setGeometry(QtCore.QRect(240, 90, 231, 20))
        self.lineEditpaciente_2.setObjectName("lineEditpaciente_2")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(30, 110, 200, 35))
        self.label_11.setMinimumSize(QtCore.QSize(200, 35))
        self.label_11.setMaximumSize(QtCore.QSize(200, 30))
        self.label_11.setObjectName("label_11")
        self.lineEditpaciente_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEditpaciente_3.setGeometry(QtCore.QRect(240, 120, 231, 20))
        self.lineEditpaciente_3.setObjectName("lineEditpaciente_3")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(30, 150, 400, 35))
        self.label_12.setMinimumSize(QtCore.QSize(400, 35))
        self.label_12.setMaximumSize(QtCore.QSize(200, 30))
        self.label_12.setObjectName("label_12")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(30, 220, 200, 35))
        self.label_18.setMinimumSize(QtCore.QSize(200, 35))
        self.label_18.setMaximumSize(QtCore.QSize(200, 30))
        self.label_18.setObjectName("label_18")
        self.lineEditpaciente_7 = QtWidgets.QLineEdit(self.frame)
        self.lineEditpaciente_7.setGeometry(QtCore.QRect(240, 260, 231, 20))
        self.lineEditpaciente_7.setObjectName("lineEditpaciente_7")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(30, 190, 200, 35))
        self.label_19.setMinimumSize(QtCore.QSize(200, 35))
        self.label_19.setMaximumSize(QtCore.QSize(200, 30))
        self.label_19.setObjectName("label_19")
        self.lineEditpaciente_8 = QtWidgets.QLineEdit(self.frame)
        self.lineEditpaciente_8.setGeometry(QtCore.QRect(240, 190, 231, 20))
        self.lineEditpaciente_8.setObjectName("lineEditpaciente_8")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(30, 250, 200, 35))
        self.label_20.setMinimumSize(QtCore.QSize(200, 35))
        self.label_20.setMaximumSize(QtCore.QSize(200, 30))
        self.label_20.setObjectName("label_20")
        self.lineEditpaciente_9 = QtWidgets.QLineEdit(self.frame)
        self.lineEditpaciente_9.setGeometry(QtCore.QRect(240, 230, 231, 20))
        self.lineEditpaciente_9.setObjectName("lineEditpaciente_9")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(30, 360, 200, 35))
        self.label_21.setMinimumSize(QtCore.QSize(200, 35))
        self.label_21.setMaximumSize(QtCore.QSize(200, 30))
        self.label_21.setObjectName("label_21")
        self.lineEditpaciente_10 = QtWidgets.QLineEdit(self.frame)
        self.lineEditpaciente_10.setGeometry(QtCore.QRect(240, 400, 231, 20))
        self.lineEditpaciente_10.setObjectName("lineEditpaciente_10")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(30, 330, 200, 35))
        self.label_22.setMinimumSize(QtCore.QSize(200, 35))
        self.label_22.setMaximumSize(QtCore.QSize(200, 30))
        self.label_22.setObjectName("label_22")
        self.lineEditpaciente_11 = QtWidgets.QLineEdit(self.frame)
        self.lineEditpaciente_11.setGeometry(QtCore.QRect(240, 330, 231, 20))
        self.lineEditpaciente_11.setObjectName("lineEditpaciente_11")
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setGeometry(QtCore.QRect(30, 390, 200, 35))
        self.label_23.setMinimumSize(QtCore.QSize(200, 35))
        self.label_23.setMaximumSize(QtCore.QSize(200, 30))
        self.label_23.setObjectName("label_23")
        self.lineEditpaciente_12 = QtWidgets.QLineEdit(self.frame)
        self.lineEditpaciente_12.setGeometry(QtCore.QRect(240, 370, 231, 20))
        self.lineEditpaciente_12.setObjectName("lineEditpaciente_12")
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setGeometry(QtCore.QRect(30, 290, 400, 35))
        self.label_24.setMinimumSize(QtCore.QSize(400, 35))
        self.label_24.setMaximumSize(QtCore.QSize(200, 30))
        self.label_24.setObjectName("label_24")
        self.lineEditpaciente_13 = QtWidgets.QLineEdit(self.frame)
        self.lineEditpaciente_13.setGeometry(QtCore.QRect(240, 480, 231, 20))
        self.lineEditpaciente_13.setObjectName("lineEditpaciente_13")
        self.lineEditpaciente_14 = QtWidgets.QLineEdit(self.frame)
        self.lineEditpaciente_14.setGeometry(QtCore.QRect(240, 520, 231, 20))
        self.lineEditpaciente_14.setObjectName("lineEditpaciente_14")
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setGeometry(QtCore.QRect(30, 480, 200, 35))
        self.label_25.setMinimumSize(QtCore.QSize(200, 35))
        self.label_25.setMaximumSize(QtCore.QSize(200, 30))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setGeometry(QtCore.QRect(30, 510, 200, 35))
        self.label_26.setMinimumSize(QtCore.QSize(200, 35))
        self.label_26.setMaximumSize(QtCore.QSize(200, 30))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setGeometry(QtCore.QRect(30, 540, 200, 35))
        self.label_27.setMinimumSize(QtCore.QSize(200, 35))
        self.label_27.setMaximumSize(QtCore.QSize(200, 30))
        self.label_27.setObjectName("label_27")
        self.lineEditpaciente_15 = QtWidgets.QLineEdit(self.frame)
        self.lineEditpaciente_15.setGeometry(QtCore.QRect(240, 550, 231, 20))
        self.lineEditpaciente_15.setObjectName("lineEditpaciente_15")
        self.label_28 = QtWidgets.QLabel(self.frame)
        self.label_28.setGeometry(QtCore.QRect(30, 440, 400, 35))
        self.label_28.setMinimumSize(QtCore.QSize(400, 35))
        self.label_28.setMaximumSize(QtCore.QSize(200, 30))
        self.label_28.setObjectName("label_28")
        self.btnmanual_3 = QtWidgets.QPushButton(self.frame)
        self.btnmanual_3.setGeometry(QtCore.QRect(490, 240, 201, 40))
        self.btnmanual_3.setMinimumSize(QtCore.QSize(100, 40))
        self.btnmanual_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        self.btnmanual_3.setIcon(icon1)
        self.btnmanual_3.setIconSize(QtCore.QSize(32, 32))
        self.btnmanual_3.setObjectName("btnmanual_3")
        self.btnmanual_4 = QtWidgets.QPushButton(self.frame)
        self.btnmanual_4.setGeometry(QtCore.QRect(490, 380, 201, 40))
        self.btnmanual_4.setMinimumSize(QtCore.QSize(100, 40))
        self.btnmanual_4.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        self.btnmanual_4.setIcon(icon1)
        self.btnmanual_4.setIconSize(QtCore.QSize(32, 32))
        self.btnmanual_4.setObjectName("btnmanual_4")
        self.btnmanual_5 = QtWidgets.QPushButton(self.frame)
        self.btnmanual_5.setGeometry(QtCore.QRect(490, 500, 201, 40))
        self.btnmanual_5.setMinimumSize(QtCore.QSize(100, 40))
        self.btnmanual_5.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        self.btnmanual_5.setIcon(icon1)
        self.btnmanual_5.setIconSize(QtCore.QSize(32, 32))
        self.btnmanual_5.setObjectName("btnmanual_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Editar_curso"))
        self.bt_regresar.setText(_translate("MainWindow", "Regresar"))
        self.btnmanual.setText(_translate("MainWindow", "Empresa"))
        self.label_8.setText(_translate("MainWindow", "Crear Empresa"))
        self.label_9.setText(_translate("MainWindow", "id"))
        self.label_10.setText(_translate("MainWindow", "nombre"))
        self.label_11.setText(_translate("MainWindow", "Abreviatura"))
        self.label_12.setText(_translate("MainWindow", "Crear Punto de atencion"))
        self.label_18.setText(_translate("MainWindow", "nombre"))
        self.label_19.setText(_translate("MainWindow", "id"))
        self.label_20.setText(_translate("MainWindow", "Direccion"))
        self.label_21.setText(_translate("MainWindow", "id escritorio"))
        self.label_22.setText(_translate("MainWindow", "id"))
        self.label_23.setText(_translate("MainWindow", "Nombre encargado"))
        self.label_24.setText(_translate("MainWindow", "Crear Escritorio"))
        self.label_25.setText(_translate("MainWindow", "id"))
        self.label_26.setText(_translate("MainWindow", "nombre"))
        self.label_27.setText(_translate("MainWindow", "tiempo"))
        self.label_28.setText(_translate("MainWindow", "Crear Transaccion"))
        self.btnmanual_3.setText(_translate("MainWindow", "Punto de Atencion"))
        self.btnmanual_4.setText(_translate("MainWindow", "Escritorio"))
        self.btnmanual_5.setText(_translate("MainWindow", "Transaccion"))
