# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\DELL\Documents\IPC2_Proyecto2_201445840\ventanas\carga_manual.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.frame.setMinimumSize(QtCore.QSize(800, 600))
        self.frame.setMaximumSize(QtCore.QSize(800, 600))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"\n"
"\n"
"QLabel{\n"
"color: rgb(18, 82, 200);\n"
"\n"
"font: 75 12pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QLabel:hover{\n"
"color: white;\n"
"\n"
"\n"
"font: 75 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Arial\";\n"
"    \n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Arial\";\n"
"    \n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bt_regresar = QtWidgets.QPushButton(self.frame)
        self.bt_regresar.setGeometry(QtCore.QRect(650, 550, 141, 40))
        self.bt_regresar.setMinimumSize(QtCore.QSize(100, 40))
        self.bt_regresar.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\IPC2_Proyecto2_201445840\\ventanas\\../imagenes/pngfind.com-back-png-1934895.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_regresar.setIcon(icon)
        self.bt_regresar.setIconSize(QtCore.QSize(32, 32))
        self.bt_regresar.setObjectName("bt_regresar")
        self.btnempresa = QtWidgets.QPushButton(self.frame)
        self.btnempresa.setGeometry(QtCore.QRect(490, 100, 201, 40))
        self.btnempresa.setMinimumSize(QtCore.QSize(100, 40))
        self.btnempresa.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\IPC2_Proyecto2_201445840\\ventanas\\../imagenes/escritura.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnempresa.setIcon(icon1)
        self.btnempresa.setIconSize(QtCore.QSize(32, 32))
        self.btnempresa.setObjectName("btnempresa")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(30, 0, 400, 35))
        self.label_8.setMinimumSize(QtCore.QSize(400, 35))
        self.label_8.setMaximumSize(QtCore.QSize(200, 30))
        self.label_8.setObjectName("label_8")
        self.lineidempresa = QtWidgets.QLineEdit(self.frame)
        self.lineidempresa.setGeometry(QtCore.QRect(240, 50, 231, 20))
        self.lineidempresa.setObjectName("lineidempresa")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(30, 50, 200, 35))
        self.label_9.setMinimumSize(QtCore.QSize(200, 35))
        self.label_9.setMaximumSize(QtCore.QSize(200, 30))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(30, 80, 200, 35))
        self.label_10.setMinimumSize(QtCore.QSize(200, 35))
        self.label_10.setMaximumSize(QtCore.QSize(200, 30))
        self.label_10.setObjectName("label_10")
        self.lineNombreempresa = QtWidgets.QLineEdit(self.frame)
        self.lineNombreempresa.setGeometry(QtCore.QRect(240, 90, 231, 20))
        self.lineNombreempresa.setObjectName("lineNombreempresa")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(30, 110, 200, 35))
        self.label_11.setMinimumSize(QtCore.QSize(200, 35))
        self.label_11.setMaximumSize(QtCore.QSize(200, 30))
        self.label_11.setObjectName("label_11")
        self.lineabreviatura = QtWidgets.QLineEdit(self.frame)
        self.lineabreviatura.setGeometry(QtCore.QRect(240, 120, 231, 20))
        self.lineabreviatura.setObjectName("lineabreviatura")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(30, 150, 400, 35))
        self.label_12.setMinimumSize(QtCore.QSize(400, 35))
        self.label_12.setMaximumSize(QtCore.QSize(200, 30))
        self.label_12.setObjectName("label_12")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(30, 220, 200, 35))
        self.label_18.setMinimumSize(QtCore.QSize(200, 35))
        self.label_18.setMaximumSize(QtCore.QSize(200, 30))
        self.label_18.setObjectName("label_18")
        self.linedireccion = QtWidgets.QLineEdit(self.frame)
        self.linedireccion.setGeometry(QtCore.QRect(240, 260, 231, 20))
        self.linedireccion.setObjectName("linedireccion")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(30, 190, 200, 35))
        self.label_19.setMinimumSize(QtCore.QSize(200, 35))
        self.label_19.setMaximumSize(QtCore.QSize(200, 30))
        self.label_19.setObjectName("label_19")
        self.lineidpunto = QtWidgets.QLineEdit(self.frame)
        self.lineidpunto.setGeometry(QtCore.QRect(240, 190, 231, 20))
        self.lineidpunto.setObjectName("lineidpunto")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(30, 250, 200, 35))
        self.label_20.setMinimumSize(QtCore.QSize(200, 35))
        self.label_20.setMaximumSize(QtCore.QSize(200, 30))
        self.label_20.setObjectName("label_20")
        self.linenombrepunto = QtWidgets.QLineEdit(self.frame)
        self.linenombrepunto.setGeometry(QtCore.QRect(240, 230, 231, 20))
        self.linenombrepunto.setObjectName("linenombrepunto")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(30, 360, 200, 35))
        self.label_21.setMinimumSize(QtCore.QSize(200, 35))
        self.label_21.setMaximumSize(QtCore.QSize(200, 30))
        self.label_21.setObjectName("label_21")
        self.linenombreencargado = QtWidgets.QLineEdit(self.frame)
        self.linenombreencargado.setGeometry(QtCore.QRect(240, 400, 231, 20))
        self.linenombreencargado.setObjectName("linenombreencargado")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(30, 330, 200, 35))
        self.label_22.setMinimumSize(QtCore.QSize(200, 35))
        self.label_22.setMaximumSize(QtCore.QSize(200, 30))
        self.label_22.setObjectName("label_22")
        self.lineidescritorio = QtWidgets.QLineEdit(self.frame)
        self.lineidescritorio.setGeometry(QtCore.QRect(240, 330, 231, 20))
        self.lineidescritorio.setObjectName("lineidescritorio")
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setGeometry(QtCore.QRect(30, 390, 200, 35))
        self.label_23.setMinimumSize(QtCore.QSize(200, 35))
        self.label_23.setMaximumSize(QtCore.QSize(200, 30))
        self.label_23.setObjectName("label_23")
        self.lineid2escritorio = QtWidgets.QLineEdit(self.frame)
        self.lineid2escritorio.setGeometry(QtCore.QRect(240, 370, 231, 20))
        self.lineid2escritorio.setObjectName("lineid2escritorio")
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setGeometry(QtCore.QRect(30, 290, 400, 35))
        self.label_24.setMinimumSize(QtCore.QSize(400, 35))
        self.label_24.setMaximumSize(QtCore.QSize(200, 30))
        self.label_24.setObjectName("label_24")
        self.lineidtransaccion = QtWidgets.QLineEdit(self.frame)
        self.lineidtransaccion.setGeometry(QtCore.QRect(240, 480, 231, 20))
        self.lineidtransaccion.setObjectName("lineidtransaccion")
        self.linenombretransaccion = QtWidgets.QLineEdit(self.frame)
        self.linenombretransaccion.setGeometry(QtCore.QRect(240, 520, 231, 20))
        self.linenombretransaccion.setObjectName("linenombretransaccion")
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setGeometry(QtCore.QRect(30, 480, 200, 35))
        self.label_25.setMinimumSize(QtCore.QSize(200, 35))
        self.label_25.setMaximumSize(QtCore.QSize(200, 30))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setGeometry(QtCore.QRect(30, 510, 200, 35))
        self.label_26.setMinimumSize(QtCore.QSize(200, 35))
        self.label_26.setMaximumSize(QtCore.QSize(200, 30))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setGeometry(QtCore.QRect(30, 540, 200, 35))
        self.label_27.setMinimumSize(QtCore.QSize(200, 35))
        self.label_27.setMaximumSize(QtCore.QSize(200, 30))
        self.label_27.setObjectName("label_27")
        self.linetiempo = QtWidgets.QLineEdit(self.frame)
        self.linetiempo.setGeometry(QtCore.QRect(240, 550, 231, 20))
        self.linetiempo.setObjectName("linetiempo")
        self.label_28 = QtWidgets.QLabel(self.frame)
        self.label_28.setGeometry(QtCore.QRect(30, 440, 400, 35))
        self.label_28.setMinimumSize(QtCore.QSize(400, 35))
        self.label_28.setMaximumSize(QtCore.QSize(200, 30))
        self.label_28.setObjectName("label_28")
        self.btnpunto = QtWidgets.QPushButton(self.frame)
        self.btnpunto.setGeometry(QtCore.QRect(490, 240, 201, 40))
        self.btnpunto.setMinimumSize(QtCore.QSize(100, 40))
        self.btnpunto.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        self.btnpunto.setIcon(icon1)
        self.btnpunto.setIconSize(QtCore.QSize(32, 32))
        self.btnpunto.setObjectName("btnpunto")
        self.btnescritorio = QtWidgets.QPushButton(self.frame)
        self.btnescritorio.setGeometry(QtCore.QRect(490, 380, 201, 40))
        self.btnescritorio.setMinimumSize(QtCore.QSize(100, 40))
        self.btnescritorio.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        self.btnescritorio.setIcon(icon1)
        self.btnescritorio.setIconSize(QtCore.QSize(32, 32))
        self.btnescritorio.setObjectName("btnescritorio")
        self.btntransacion = QtWidgets.QPushButton(self.frame)
        self.btntransacion.setGeometry(QtCore.QRect(490, 500, 201, 40))
        self.btntransacion.setMinimumSize(QtCore.QSize(100, 40))
        self.btntransacion.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        self.btntransacion.setIcon(icon1)
        self.btntransacion.setIconSize(QtCore.QSize(32, 32))
        self.btntransacion.setObjectName("btntransacion")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Editar_curso"))
        self.bt_regresar.setText(_translate("MainWindow", "Regresar"))
        self.btnempresa.setText(_translate("MainWindow", "Empresa"))
        self.label_8.setText(_translate("MainWindow", "Crear Empresa"))
        self.label_9.setText(_translate("MainWindow", "id"))
        self.label_10.setText(_translate("MainWindow", "nombre"))
        self.label_11.setText(_translate("MainWindow", "Abreviatura"))
        self.label_12.setText(_translate("MainWindow", "Crear Punto de atencion"))
        self.label_18.setText(_translate("MainWindow", "nombre"))
        self.label_19.setText(_translate("MainWindow", "id"))
        self.label_20.setText(_translate("MainWindow", "Direccion"))
        self.label_21.setText(_translate("MainWindow", "id escritorio"))
        self.label_22.setText(_translate("MainWindow", "id"))
        self.label_23.setText(_translate("MainWindow", "Nombre encargado"))
        self.label_24.setText(_translate("MainWindow", "Crear Escritorio"))
        self.label_25.setText(_translate("MainWindow", "id"))
        self.label_26.setText(_translate("MainWindow", "nombre"))
        self.label_27.setText(_translate("MainWindow", "tiempo"))
        self.label_28.setText(_translate("MainWindow", "Crear Transaccion"))
        self.btnpunto.setText(_translate("MainWindow", "Punto de Atencion"))
        self.btnescritorio.setText(_translate("MainWindow", "Escritorio"))
        self.btntransacion.setText(_translate("MainWindow", "Transaccion"))
