# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\DELL\Documents\IPC2_Proyecto2_201445840\ventanas\simular_punto.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.frame.setMinimumSize(QtCore.QSize(800, 600))
        self.frame.setMaximumSize(QtCore.QSize(800, 600))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"\n"
"\n"
"QLabel{\n"
"color: rgb(18, 82, 200);\n"
"\n"
"font: 75 12pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QLabel:hover{\n"
"color: white;\n"
"\n"
"\n"
"font: 75 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Arial\";\n"
"    \n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Arial\";\n"
"    \n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bt_regresar = QtWidgets.QPushButton(self.frame)
        self.bt_regresar.setGeometry(QtCore.QRect(650, 550, 141, 40))
        self.bt_regresar.setMinimumSize(QtCore.QSize(100, 40))
        self.bt_regresar.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\IPC2_Proyecto2_201445840\\ventanas\\../imagenes/pngfind.com-back-png-1934895.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_regresar.setIcon(icon)
        self.bt_regresar.setIconSize(QtCore.QSize(32, 32))
        self.bt_regresar.setObjectName("bt_regresar")
        self.btnempresa = QtWidgets.QPushButton(self.frame)
        self.btnempresa.setGeometry(QtCore.QRect(580, 310, 201, 40))
        self.btnempresa.setMinimumSize(QtCore.QSize(100, 40))
        self.btnempresa.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\DELL\\Documents\\IPC2_Proyecto2_201445840\\ventanas\\../imagenes/escritura.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnempresa.setIcon(icon1)
        self.btnempresa.setIconSize(QtCore.QSize(32, 32))
        self.btnempresa.setObjectName("btnempresa")
        self.labelpunto = QtWidgets.QLabel(self.frame)
        self.labelpunto.setGeometry(QtCore.QRect(30, 0, 400, 35))
        self.labelpunto.setMinimumSize(QtCore.QSize(400, 35))
        self.labelpunto.setMaximumSize(QtCore.QSize(200, 30))
        self.labelpunto.setObjectName("labelpunto")
        self.labelescriactivo = QtWidgets.QLabel(self.frame)
        self.labelescriactivo.setGeometry(QtCore.QRect(30, 50, 400, 35))
        self.labelescriactivo.setMinimumSize(QtCore.QSize(400, 35))
        self.labelescriactivo.setMaximumSize(QtCore.QSize(200, 30))
        self.labelescriactivo.setObjectName("labelescriactivo")
        self.labelescridesactivo = QtWidgets.QLabel(self.frame)
        self.labelescridesactivo.setGeometry(QtCore.QRect(30, 80, 400, 35))
        self.labelescridesactivo.setMinimumSize(QtCore.QSize(400, 35))
        self.labelescridesactivo.setMaximumSize(QtCore.QSize(200, 30))
        self.labelescridesactivo.setObjectName("labelescridesactivo")
        self.labelclienteespera = QtWidgets.QLabel(self.frame)
        self.labelclienteespera.setGeometry(QtCore.QRect(30, 110, 400, 35))
        self.labelclienteespera.setMinimumSize(QtCore.QSize(400, 35))
        self.labelclienteespera.setMaximumSize(QtCore.QSize(200, 30))
        self.labelclienteespera.setObjectName("labelclienteespera")
        self.labeltiempopromedioespera = QtWidgets.QLabel(self.frame)
        self.labeltiempopromedioespera.setGeometry(QtCore.QRect(30, 150, 400, 35))
        self.labeltiempopromedioespera.setMinimumSize(QtCore.QSize(400, 35))
        self.labeltiempopromedioespera.setMaximumSize(QtCore.QSize(200, 30))
        self.labeltiempopromedioespera.setObjectName("labeltiempopromedioespera")
        self.labeltiempominespera = QtWidgets.QLabel(self.frame)
        self.labeltiempominespera.setGeometry(QtCore.QRect(30, 220, 400, 35))
        self.labeltiempominespera.setMinimumSize(QtCore.QSize(400, 35))
        self.labeltiempominespera.setMaximumSize(QtCore.QSize(200, 30))
        self.labeltiempominespera.setObjectName("labeltiempominespera")
        self.labeltiempomaxespera = QtWidgets.QLabel(self.frame)
        self.labeltiempomaxespera.setGeometry(QtCore.QRect(30, 190, 400, 35))
        self.labeltiempomaxespera.setMinimumSize(QtCore.QSize(400, 35))
        self.labeltiempomaxespera.setMaximumSize(QtCore.QSize(200, 30))
        self.labeltiempomaxespera.setObjectName("labeltiempomaxespera")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(260, 360, 200, 35))
        self.label_21.setMinimumSize(QtCore.QSize(200, 35))
        self.label_21.setMaximumSize(QtCore.QSize(200, 30))
        self.label_21.setObjectName("label_21")
        self.labeltiempominatencion = QtWidgets.QLabel(self.frame)
        self.labeltiempominatencion.setGeometry(QtCore.QRect(30, 330, 400, 35))
        self.labeltiempominatencion.setMinimumSize(QtCore.QSize(400, 35))
        self.labeltiempominatencion.setMaximumSize(QtCore.QSize(200, 30))
        self.labeltiempominatencion.setObjectName("labeltiempominatencion")
        self.labeltiempomaxatencion = QtWidgets.QLabel(self.frame)
        self.labeltiempomaxatencion.setGeometry(QtCore.QRect(30, 290, 400, 35))
        self.labeltiempomaxatencion.setMinimumSize(QtCore.QSize(400, 35))
        self.labeltiempomaxatencion.setMaximumSize(QtCore.QSize(200, 30))
        self.labeltiempomaxatencion.setObjectName("labeltiempomaxatencion")
        self.btnporescritorio = QtWidgets.QPushButton(self.frame)
        self.btnporescritorio.setGeometry(QtCore.QRect(650, 420, 141, 40))
        self.btnporescritorio.setMinimumSize(QtCore.QSize(100, 40))
        self.btnporescritorio.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        self.btnporescritorio.setIcon(icon1)
        self.btnporescritorio.setIconSize(QtCore.QSize(32, 32))
        self.btnporescritorio.setObjectName("btnporescritorio")
        self.labeltiempopromedioatencion = QtWidgets.QLabel(self.frame)
        self.labeltiempopromedioatencion.setGeometry(QtCore.QRect(30, 250, 400, 35))
        self.labeltiempopromedioatencion.setMinimumSize(QtCore.QSize(400, 35))
        self.labeltiempopromedioatencion.setMaximumSize(QtCore.QSize(200, 30))
        self.labeltiempopromedioatencion.setObjectName("labeltiempopromedioatencion")
        self.textEditinfo = QtWidgets.QTextEdit(self.frame)
        self.textEditinfo.setGeometry(QtCore.QRect(30, 400, 611, 191))
        self.textEditinfo.setObjectName("textEditinfo")
        self.btnsimular = QtWidgets.QPushButton(self.frame)
        self.btnsimular.setGeometry(QtCore.QRect(570, 30, 201, 40))
        self.btnsimular.setMinimumSize(QtCore.QSize(100, 40))
        self.btnsimular.setStyleSheet("QPushButton{\n"
"background-color: rgb(18, 82, 200);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"\n"
"font: 75 11pt \"Arial Black\";\n"
"}")
        self.btnsimular.setIcon(icon1)
        self.btnsimular.setIconSize(QtCore.QSize(32, 32))
        self.btnsimular.setObjectName("btnsimular")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Editar_curso"))
        self.bt_regresar.setText(_translate("MainWindow", "Regresar"))
        self.btnempresa.setText(_translate("MainWindow", "Punto de atencion"))
        self.labelpunto.setText(_translate("MainWindow", "Punto atencion"))
        self.labelescriactivo.setText(_translate("MainWindow", "Escritorios activos"))
        self.labelescridesactivo.setText(_translate("MainWindow", "Escritorios Inactivos"))
        self.labelclienteespera.setText(_translate("MainWindow", "Clientes en espera"))
        self.labeltiempopromedioespera.setText(_translate("MainWindow", "Tiempo promedio de espera"))
        self.labeltiempominespera.setText(_translate("MainWindow", "Tiempo min espera"))
        self.labeltiempomaxespera.setText(_translate("MainWindow", "Tiempo max de espera "))
        self.label_21.setText(_translate("MainWindow", "POR ESCRITORIO"))
        self.labeltiempominatencion.setText(_translate("MainWindow", "Tiempo min atencion"))
        self.labeltiempomaxatencion.setText(_translate("MainWindow", "Tiempo max atencion"))
        self.btnporescritorio.setText(_translate("MainWindow", "Escritorios"))
        self.labeltiempopromedioatencion.setText(_translate("MainWindow", "Tiempo promedio de atencion"))
        self.textEditinfo.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btnsimular.setText(_translate("MainWindow", "simular"))
